paths:
  /auth/login:
    get:
      tags:
          - Task Management
      summary: Get all tasks
      description: Returns a list of all tasks
      responses:
        "200":
          description: A JSON array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./tasks-defs.yaml#/components/schemas/Task"
        # post:
        #   tags:
        #     - Task Management
        #   summary: Create a new task
        #   description: Add a new task
        #   requestBody:
        #     required: true
        #     content:
        #       application/json:
        #         schema:
        #           $ref: "./tasks-defs.yaml#/components/schemas/Task"
        #   responses:
        #     "201":
        #       description: Task created successfully
        #       content:
        #         application/json:
        #           schema:
        #             $ref: "./tasks-defs.yaml#/components/schemas/Task"
