components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "987e6543-e21b-45d6-a789-426614174111"
        title:
          type: string
          example: "Finish homework"
        description:
          type: string
          example: "Complete math and science homework by tonight"
        status:
          type: string
          enum: [pending, in-progress, done]
          example: "pending"
        assignedTo:
          $ref: "../users/users-defs.yaml#/components/schemas/User"
      required:
        - id
        - title
        - status
