paths:
  /tasks:
    get:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Get all tasks
      responses:
        "200":
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../schemas/schema.yaml#/components/schemas/Task"

    post:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/schema.yaml#/components/schemas/CreateTask"
      responses:
        "201":
          description: Task created

  /tasks/{taskId}:
    delete:
      tags:
        - Task Management
      security:
        - bearerAuth: []
      summary: Delete task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Task deleted
